### ISSUE TITLE
How to know Debezium tail log

### ISSUE THREAD

**Issue by ankit45621** [ivangfr/springboot-kafka-debezium-ksql#1]
All working fine Thank for sample.But i want to know one thing that when we insert entry in review table then where we can see that activity log?

**Comment by ivangfr** [comment]
Hi @ankit45621 what kind of activity log you would like to see (MySQL logs, events in Kafka, etc)?

**Comment by ankit45621** [comment]
I want to know debezium tail f log.

**Comment by ankit45621** [comment]
I am new with this integration.  Please let me know if there is any log like debezium tail f log.

**Comment by ivangfr** [comment]
Ok. I will investigate about it. I let you know.

**Comment by ivangfr** [comment]
Hey @ankit45621 

I've checked about your question. `Debezium` is a connector that is installed into `Kafka Connect`. So, in order to check `Debezium` logs, you should see `Kafka Connect` docker container logs.

My code, as it is, has logging level `INFO` for `Kafka Connect` container. It doesn't log too much. In order to log more, go to `docker-compose.yml` and change the `kafka-connect` environment variable `CONNECT_LOG4J_ROOT_LOGLEVEL` from `INFO` to `DEBUG`.

In order to see the logs from `kafka-connect` docker container, run
```
docker logs kafka-connect -f
```

You can filter the output using `grep`
```
docker logs kafka-connect -f | grep debezium
```

I hope you can find the logs you want. Btw, I've simulated locally and it shows a lot of things.

I hope I have helped somehow. If you have more questions, don't hesitate to contact me.

**Comment by ankit45621** [comment]
@ivangfr Thank a lot. This is what i was looking.
