### ISSUE TITLE
Caused by: org.apache.kafka.connect.errors.ConnectException: PK mode for table 

### ISSUE THREAD

**Issue by ankit45621** [ivangfr/springboot-kafka-debezium-ksql#7]
Hi,
While running JDBC sink connector I am getting following error:

Caused by: org.apache.kafka.connect.errors.ConnectException: PK mode for table 'qa_buyer_tax_rules' is RECORD_KEY with configured PK fields [id], but record key schema does not contain field: id

I am using:

    "auto.create": "true",
    "insert.mode":"upsert",
    "pk.mode":"record_key",
    "pk.fields":"id",
    "auto.evolve":"true",

configuration in my sink connector configuration but in my source table there is no id column available. Can you please suggest solution?

**Comment by ivangfr** [comment]
As far as I know, JDBC connector requires that a table has an id (new records has bigger ids) and/or some updated/timestamp field so that it can keep track of what is new in the table and push it to Kafka. Please check https://docs.confluent.io/3.0.0/connect/connect-jdbc/docs/jdbc_connector.html#incremental-query-modes
- What is the primary key of your source table?
- Does your source table have any kind of timestamp field that records when the row was created/updated?

**Comment by ankit45621** [comment]
1. there is no primary key in my source table
2. yes there is created but i am using transforms for this configuration

**Comment by ankit45621** [comment]
I solved this by creating seperate sink for table having pk with different field name. 

Thanks
